/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler . */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

#include <iostream>
#include "adf/adf_api/AIEControlConfig.h"


/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "topStencil", nullptr, nullptr, nullptr, {7, 7, 7}, {1, 2, 3}, {7, 7, 8}, {0, 1, 3}, {0x4, 0x6804, 0x4}, {0, 0, 0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;

/************************** PLIO Configurations  *****************************/

  adf::PLIOConfig PLIOConfigurations[] = {
  //{id, name, loginal_name, shim_column, slaveOrMaster, streamId}
    {0, "topStencil.in_plio[0]", "hdiff_in0", 7, 0, 5},
    {1, "topStencil.in_plio[1]", "hdiff_in1", 6, 0, 1},
    {2, "topStencil.in_plio[2]", "hdiff_in2", 7, 0, 2},
    {3, "topStencil.in_plio[3]", "hdiff_in3", 7, 0, 0},
    {4, "topStencil.in_plio[4]", "hdiff_in4", 7, 0, 6},
    {5, "topStencil.in_plio[5]", "hdiff_in5", 7, 0, 1},
    {6, "topStencil.in_plio[6]", "hdiff_in6", 7, 0, 4},
    {7, "topStencil.in_plio[7]", "hdiff_in7", 6, 0, 4},
    {8, "topStencil.out_plio", "hdiff_out0", 7, 1, 0},
  };
  const int NUM_PLIO = 9;


/************************** ADF API initializer *****************************/

  class InitializeAIEControlXRT
  {
  public:
    InitializeAIEControlXRT()
    {
      std::cout<<"Initializing ADF API..."<<std::endl;
#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif
      adf::initializeConfigurations(nullptr, 0, 0, 0,
                                    GraphConfigurations, NUM_GRAPH,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    PLIOConfigurations, NUM_PLIO,
                                    nullptr, 0, 0, nullptr,
                                    false, exclude_pl_control, false, nullptr,
                                    true, 2);

    }
  } initAIEControlXRT;



#if !defined(__CDO__) && !defined(__AIECONTROLCODE__)

// Kernel Stub Definition
  void hdiff_flux1(input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,output_window<int> *,output_window<int> *,output_window<int> *,output_window<int> *,output_window<int> *) { /* Stub */ } 
  void hdiff_flux2(input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,output_window<int> *) { /* Stub */ } 
  void hdiff_lap(input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,input_window<int> *,output_window<int> *,output_window<int> *,output_window<int> *,output_window<int> *) { /* Stub */ } 
#endif
